
version: 2

models:
  - name: int_current_staff
    description: "Interim current staff"
    +schema: interim
    columns:
      - name: staff_id
        data_tests:
          - not_null
          - unique
      - name: ingested_date
        data_tests:
          - not_null
      - name: ingested_from
        data_tests:
          - not_null
  - name: int_staff_mobility
    description: "Interim staff mobility"
    +schema: interim
    columns:
      - name: unique_key
        data_tests:
          - not_null
          - unique
      - name: staff_id
        data_tests:
          - not_null
      - name: ingested_date
        data_tests:
          - not_null
  - name: int_all_staff
    description: "Interim all staff"
    +schema: interim
    columns:
      - name: staff_id
        data_tests:
          - not_null
          - unique
      - name: staff_name
        data_tests:
          - not_null
      - name: staff_username
        data_tests:
          - not_null
      - name: staff_email
        data_tests:
          - not_null
      - name: staff_created_at
        data_tests:
          - not_null