/*
    Preference for Engagement Types: Understand whether customers and projects lean more towards New, Recurring, or One-time engagements.
    Revenue by Engagement Type: Quantify the revenue generated by each engagement type.
*/

SELECT 
    engagement_type,
    COUNT(*) AS total_engagements,
    SUM(total_revenue_usd) AS total_revenue
FROM customer_engagement_summary
GROUP BY engagement_type
ORDER BY total_engagements DESC;