
version: 2

models:
  - name: fact_staff_data
    description: "Fact staff data"
    +schema: operations
    columns:
      - name: staff_id
        data_tests:
          - not_null
      - name: staff_name
        data_tests:
          - not_null
      - name: staff_username
        data_tests:
          - not_null
      - name: staff_email
        data_tests:
          - not_null
  # - name: reverse_geocoding
  
  #   # Document within the same codebase
  #   description: My transformation written in Python
    
  #   # Configure in ways that feel intuitive and familiar
  #   config:
  #     materialized: view
  #     tags: ['python']  